### ISSUE TITLE
lorsqu'un planning contient des slots mais pas de solutions alors la page conflicts crash

### ISSUE THREAD

**Issue by guersbru** [ChriGau/caplanpourmoi#93]
2018-02-08T14:40:48.504888+00:00 app[web.1]: F, [2018-02-08T14:40:48.504808 #4] FATAL -- : [58131574-83c1-4881-895f-3c576cf1b683]   
2018-02-08T14:40:48.505042+00:00 app[web.1]: F, [2018-02-08T14:40:48.504964 #4] FATAL -- : [58131574-83c1-4881-895f-3c576cf1b683] NoMethodError (undefined method `user_id' for nil:NilClass):
2018-02-08T14:40:48.505139+00:00 app[web.1]: F, [2018-02-08T14:40:48.505071 #4] FATAL -- : [58131574-83c1-4881-895f-3c576cf1b683]   
2018-02-08T14:40:48.505248+00:00 app[web.1]: F, [2018-02-08T14:40:48.505178 #4] FATAL -- : [58131574-83c1-4881-895f-3c576cf1b683] app/controllers/plannings_controller.rb:61:in `block in conflicts'
2018-02-08T14:40:48.505252+00:00 app[web.1]: [58131574-83c1-4881-895f-3c576cf1b683] app/controllers/plannings_controller.rb:58:in `conflicts'
2018-02-08T14:40:48.941832+00:00 app[web.1]: F, [2018-02-08T14:40:48.941750 #4] FATAL -- : [417d8630-3ab5-4567-a1f6-db826463b2bc] ActionController::RoutingError (No route matches [GET] "/plannings/4/images/logo%20cppm.png"):

**Comment by ChriGau** [comment]
Traité via pull request #97 (kill-user-in-slot)
